# Generated by Django 5.2.4 on 2025-10-27 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brinvest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wacth_list',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='Brinvest.asset'),
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('dividend_policy', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etf_profile', to='Brinvest.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_type', models.CharField(blank=True, max_length=100, null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_profile', to='Brinvest.asset')),
            ],
        ),
        migrations.CreateModel(
            name='ETFComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage weight (0-100)', max_digits=5)),
                ('etf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Brinvest.etf')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etf_components', to='Brinvest.stock')),
            ],
        ),
    ]
