# Generated by Django 5.2.4 on 2025-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brinvest', '0003_asset_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
